defmodule Storyarn.Exports.Serializers.GodotDialogic do
  @moduledoc """
  Godot Dialogic 2 serializer.

  Produces `.dtl` timeline files for Dialogic 2, the dominant dialogue addon
  for the Godot engine (~5.2k stars). Each flow becomes one `.dtl` file.

  ## Output

  Returns `{:ok, [{filename, content}, ...]}` with:
  - `.dtl` file(s) — one per flow
  - `metadata.json` — character/variable/timeline mapping
  """

  @behaviour Storyarn.Exports.Serializer

  alias Storyarn.Exports.ExportOptions
  alias Storyarn.Exports.ExpressionTranspiler
  alias Storyarn.Exports.Serializers.GraphTraversal
  alias Storyarn.Exports.Serializers.Helpers

  @impl true
  def content_type, do: "text/plain"

  @impl true
  def file_extension, do: "dtl"

  @impl true
  def format_label, do: "Godot Dialogic (.dtl)"

  @impl true
  def supported_sections, do: [:flows, :sheets]

  @impl true
  def serialize(project_data, %ExportOptions{} = _opts) do
    sheets = project_data.sheets || []
    flows = project_data.flows || []
    variables = Helpers.collect_variables(sheets)
    speaker_map = Helpers.build_speaker_map(sheets)
    flow_shortcuts_by_id = flow_shortcuts_by_id(flows)
    return_targets = collect_return_targets(flows, flow_shortcuts_by_id)

    dtl_files =
      Enum.map(flows, fn flow ->
        filename = flow_filename(flow)
        content = flow_to_dtl(flow, speaker_map, flow_shortcuts_by_id, return_targets)
        {filename, content}
      end)

    metadata = build_metadata(project_data.project, sheets, variables, flows)

    {:ok, dtl_files ++ [{"metadata.json", Jason.encode!(metadata, pretty: true)}]}
  end

  @impl true
  def serialize_to_file(_data, _file_path, _options, _callbacks) do
    {:error, :not_implemented}
  end

  # ---------------------------------------------------------------------------
  # Flow → .dtl
  # ---------------------------------------------------------------------------

  defp flow_to_dtl(flow, speaker_map, flow_shortcuts_by_id, return_targets) do
    {instructions, hub_sections} = GraphTraversal.linearize_blocks(flow)

    ctx = %{
      speaker_map: speaker_map,
      flow_shortcuts_by_id: flow_shortcuts_by_id,
      is_return_target: MapSet.member?(return_targets, flow.shortcut)
    }

    header = "# Generated by Storyarn — Dialogic 2 timeline"
    body = render_instructions(instructions, ctx, 0)

    hub_blocks =
      Enum.flat_map(hub_sections, fn {label, instrs} ->
        ["", "label #{label}"] ++ render_instructions(instrs, ctx, 0)
      end)

    lines = [header, ""] ++ body ++ hub_blocks
    Enum.join(lines, "\n") <> "\n"
  end

  defp flow_filename(flow) do
    name = Helpers.shortcut_to_identifier(flow.shortcut || flow.name || "flow_#{flow.id}")
    "#{name}.dtl"
  end

  # ---------------------------------------------------------------------------
  # Instruction rendering
  # ---------------------------------------------------------------------------

  defp render_instructions(instructions, ctx, depth) do
    Enum.flat_map(instructions, &render_instruction(&1, ctx, depth))
  end

  defp render_instruction({:dialogue, node}, ctx, depth) do
    data = node.data || %{}
    text = data |> Helpers.dialogue_text() |> escape_dtl_text()
    speaker = Helpers.speaker_name(data, ctx.speaker_map)
    stage_dirs = Helpers.strip_html(data["stage_directions"] || "")

    dialogue_line =
      if speaker do
        "#{indent(depth)}#{speaker}: #{text}"
      else
        "#{indent(depth)}#{text}"
      end

    stage_line =
      if stage_dirs == "" do
        []
      else
        ["#{indent(depth)}# [Stage: #{stage_dirs}]"]
      end

    [dialogue_line] ++ stage_line
  end

  defp render_instruction({:choices_start, _node}, _ctx, _depth), do: []

  defp render_instruction({:choices, _node, branches}, ctx, depth) do
    Enum.flat_map(branches, fn {response, index, body} ->
      render_instruction({:choice, response, index}, ctx, depth) ++
        render_instructions(body, ctx, depth + 1)
    end)
  end

  defp render_instruction({:choice, resp, _idx}, _ctx, depth) do
    text =
      (resp["text"] || resp["menu_text"] || "")
      |> Helpers.strip_html()
      |> escape_dtl_text()

    condition = build_dtl_condition(resp["condition"])

    choice_line =
      if condition do
        "#{indent(depth)}- #{text} | [if #{condition}]"
      else
        "#{indent(depth)}- #{text}"
      end

    assign_lines =
      case resp["instruction_assignments"] do
        [_ | _] = assignments ->
          case ExpressionTranspiler.transpile_instruction(assignments, :godot) do
            {:ok, expr, _} when expr != "" ->
              expr |> String.split("\n") |> Enum.map(&"#{indent(depth + 1)}#{&1}")

            _ ->
              []
          end

        _ ->
          []
      end

    [choice_line | assign_lines]
  end

  defp render_instruction({:choices_end, _node}, _ctx, _depth), do: []

  defp render_instruction({:condition, node, branches}, ctx, depth) do
    if switch_condition?(node) do
      render_switch_condition(node, branches, ctx, depth)
    else
      render_boolean_condition(node, branches, ctx, depth)
    end
  end

  defp render_instruction({:condition_start, node}, _ctx, depth) do
    data = node.data || %{}
    condition = Helpers.extract_condition(data["condition"])

    case ExpressionTranspiler.transpile_condition(condition, :godot) do
      {:ok, expr, _} when expr != "" ->
        ["#{indent(depth)}if #{expr}:"]

      _ ->
        ["#{indent(depth)}if true:"]
    end
  end

  defp render_instruction({:condition_branch, _pin, _label, idx}, _ctx, depth) do
    case idx do
      0 -> []
      1 -> ["#{indent(depth)}else:"]
      n -> ["#{indent(depth)}# (branch #{n})"]
    end
  end

  # Dialogic uses de-indentation to end blocks — no explicit end marker
  defp render_instruction({:condition_end, _node}, _ctx, _depth), do: []

  defp render_instruction({:instruction, node}, _ctx, depth) do
    data = node.data || %{}
    assignments = Helpers.extract_assignments(data)

    case ExpressionTranspiler.transpile_instruction(assignments, :godot) do
      {:ok, expr, _} when expr != "" ->
        expr |> String.split("\n") |> Enum.map(&"#{indent(depth)}#{&1}")

      _ ->
        []
    end
  end

  defp render_instruction({:subflow, node}, ctx, depth) do
    data = node.data || %{}
    target = Helpers.shortcut_to_identifier(resolve_flow_shortcut(data, ctx) || "subflow_#{node.id}")
    ["#{indent(depth)}jump #{target}/"]
  end

  defp render_instruction({:jump, node, target_label}, _ctx, depth) do
    target =
      if get_in(node.data || %{}, ["target_flow_shortcut"]) do
        "#{target_label}/"
      else
        target_label
      end

    ["#{indent(depth)}jump #{target}"]
  end

  defp render_instruction({:divert, target_label}, _ctx, depth) do
    ["#{indent(depth)}jump #{target_label}"]
  end

  defp render_instruction({:exit, node}, ctx, depth) do
    data = node.data || %{}

    case data["exit_mode"] do
      "flow_reference" ->
        target = Helpers.shortcut_to_identifier(resolve_flow_shortcut(data, ctx) || "unknown")
        ["#{indent(depth)}jump #{target}/"]

      "caller_return" ->
        ["#{indent(depth)}return"]

      _mode ->
        [terminal_command(ctx, depth)]
    end
  end

  defp render_instruction(_, _ctx, _depth), do: []

  defp render_boolean_condition(node, branches, ctx, depth) do
    render_instruction({:condition_start, node}, ctx, depth) ++
      Enum.flat_map(branches, fn {pin, label, index, body} ->
        render_instruction({:condition_branch, pin, label, index}, ctx, depth) ++
          render_instructions(body, ctx, depth + 1)
      end)
  end

  defp render_switch_condition(node, branches, ctx, depth) do
    branches
    |> Enum.with_index()
    |> Enum.flat_map(fn {{pin, _label, _index, body}, rendered_index} ->
      render_switch_branch(node, pin, rendered_index, depth) ++
        render_instructions(body, ctx, depth + 1)
    end)
  end

  defp render_switch_branch(node, pin, index, depth) do
    keyword = if index == 0, do: "if", else: "elif"
    expr = switch_branch_condition(node, pin) || "true"
    ["#{indent(depth)}#{keyword} #{expr}:"]
  end

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp escape_dtl_text(text) when is_binary(text) do
    text
    |> String.replace("\\", "\\\\")
    |> String.replace("#", "\\#")
    |> String.replace("{", "\\{")
    |> String.replace("}", "\\}")
    |> String.replace("[", "\\[")
    |> String.replace("]", "\\]")
  end

  defp escape_dtl_text(_), do: ""

  defp terminal_command(%{is_return_target: true}, depth), do: "#{indent(depth)}return"
  defp terminal_command(_ctx, depth), do: "#{indent(depth)}[end_timeline]"

  defp flow_shortcuts_by_id(flows) do
    Map.new(flows, fn flow -> {to_string(flow.id), flow.shortcut} end)
  end

  defp collect_return_targets(flows, flow_shortcuts_by_id) do
    flows
    |> Enum.flat_map(fn flow ->
      (flow.nodes || [])
      |> Enum.filter(&(&1.type == "subflow"))
      |> Enum.map(&resolve_flow_shortcut(&1.data || %{}, flow_shortcuts_by_id))
      |> Enum.reject(&blank?/1)
    end)
    |> MapSet.new()
  end

  defp resolve_flow_shortcut(data, %{flow_shortcuts_by_id: flow_shortcuts_by_id}) do
    resolve_flow_shortcut(data, flow_shortcuts_by_id)
  end

  defp resolve_flow_shortcut(data, flow_shortcuts_by_id) do
    data["flow_shortcut"] ||
      data["referenced_flow_shortcut"] ||
      flow_shortcuts_by_id[to_string(data["referenced_flow_id"])]
  end

  defp blank?(nil), do: true
  defp blank?(""), do: true
  defp blank?(_value), do: false

  # Dialogic uses TAB characters for indentation
  defp indent(0), do: ""
  defp indent(n), do: String.duplicate("\t", n)

  defp build_dtl_condition(nil), do: nil
  defp build_dtl_condition(""), do: nil

  defp build_dtl_condition(condition) do
    parsed = Helpers.extract_condition(condition)

    case ExpressionTranspiler.transpile_condition(parsed, :godot) do
      {:ok, expr, _} when expr != "" -> expr
      _ -> nil
    end
  end

  defp switch_condition?(%{data: %{"switch_mode" => true}}), do: true
  defp switch_condition?(_node), do: false

  defp switch_branch_condition(%{data: data}, pin) when is_map(data) do
    data["condition"]
    |> Helpers.extract_condition()
    |> switch_case_condition(pin)
    |> build_dtl_condition()
  end

  defp switch_branch_condition(_node, _pin), do: nil

  defp switch_case_condition(%{"blocks" => blocks}, pin) when is_list(blocks) do
    Enum.find_value(blocks, fn
      %{"type" => "block", "id" => ^pin} = block ->
        %{
          "logic" => block["logic"] || "all",
          "blocks" => [block]
        }

      _block ->
        nil
    end)
  end

  defp switch_case_condition(%{"rules" => rules}, pin) when is_list(rules) do
    Enum.find_value(rules, fn
      %{"id" => ^pin} = rule ->
        %{
          "logic" => "all",
          "blocks" => [
            %{
              "type" => "block",
              "logic" => "all",
              "rules" => [rule]
            }
          ]
        }

      _rule ->
        nil
    end)
  end

  defp switch_case_condition(_condition, _pin), do: nil

  # ---------------------------------------------------------------------------
  # Metadata
  # ---------------------------------------------------------------------------

  defp build_metadata(project, sheets, variables, flows) do
    characters =
      Map.new(sheets, fn sheet ->
        properties =
          sheet.blocks
          |> Enum.reject(& &1.is_constant)
          |> Enum.filter(&(is_binary(&1.variable_name) and &1.variable_name != ""))
          |> Map.new(fn block ->
            {block.variable_name,
             %{
               "type" => to_string(Helpers.infer_variable_type(block)),
               "default" => Helpers.infer_default_value(block)
             }}
          end)

        {sheet.shortcut,
         %{
           "display_name" => sheet.name,
           "storyarn_shortcut" => sheet.shortcut,
           "properties" => properties
         }}
      end)

    variable_folders = build_variable_folders(variables)

    timeline_mapping =
      Map.new(flows, fn flow ->
        key = flow.shortcut || flow.name
        {key, flow_filename(flow)}
      end)

    %{
      "storyarn_dialogic_metadata" => "1.0.0",
      "project" => project.name,
      "characters" => characters,
      "variable_folders" => variable_folders,
      "timeline_mapping" => timeline_mapping
    }
  end

  defp build_variable_folders(variables) do
    variables
    |> Enum.group_by(fn var ->
      Helpers.shortcut_to_identifier(var.sheet_shortcut)
    end)
    |> Map.new(fn {folder, vars} ->
      folder_vars = Map.new(vars, fn var -> {var.variable_name, var.default} end)
      {folder, folder_vars}
    end)
  end
end
