defmodule Storyarn.Exports.Serializers.Ink do
  @moduledoc """
  Ink script serializer.

  Produces `.ink` text source files for the Ink narrative scripting runtime.
  Reaches ~90% of game developers via 13+ engine runtimes.

  ## Output

  Returns `{:ok, [{filename, content}, ...]}` with:
  - `{project_name}.ink` — main Ink source file
  - `metadata.json` — character/variable mapping sidecar
  """

  @behaviour Storyarn.Exports.Serializer

  alias Storyarn.Exports.ExportOptions
  alias Storyarn.Exports.ExpressionTranspiler
  alias Storyarn.Exports.LocalizationCatalog
  alias Storyarn.Exports.Serializers.GraphTraversal
  alias Storyarn.Exports.Serializers.Helpers
  alias Storyarn.Localization.SourceContract

  @impl true
  def content_type, do: "text/plain"

  @impl true
  def file_extension, do: "ink"

  @impl true
  def format_label, do: "Ink (.ink)"

  @impl true
  def supported_sections, do: [:flows, :sheets, :localization]

  @impl true
  def localization_mode, do: :external_catalog

  @impl true
  def serialize(project_data, %ExportOptions{} = opts) do
    sheets = project_data.sheets || []
    flows = project_data.flows || []
    variables = Helpers.collect_variables(sheets)
    speaker_map = Helpers.build_speaker_map(sheets)
    flow_shortcuts_by_id = flow_shortcuts_by_id(flows)
    tunnel_targets = collect_tunnel_targets(flows, flow_shortcuts_by_id)

    ink_lines =
      List.flatten([
        header_lines(project_data.project),
        variable_declaration_lines(variables),
        Enum.flat_map(flows, &flow_to_knot(&1, speaker_map, flow_shortcuts_by_id, tunnel_targets))
      ])

    ink_source =
      ink_lines
      |> Enum.intersperse("\n")
      |> IO.iodata_to_binary()

    project_name = Helpers.shortcut_to_identifier(project_data.project.slug || "story")

    metadata = build_metadata(project_data.project, sheets, variables)

    files = [
      {"#{project_name}.ink", ink_source},
      {"metadata.json", Jason.encode!(metadata, pretty: true)}
    ]

    {:ok, files ++ LocalizationCatalog.files(Map.get(project_data, :localization), opts, :generic)}
  end

  @impl true
  def serialize_to_file(_data, _file_path, _options, _callbacks) do
    {:error, :not_implemented}
  end

  # ---------------------------------------------------------------------------
  # Header
  # ---------------------------------------------------------------------------

  defp header_lines(project) do
    [
      "// Generated by Storyarn (https://storyarn.dev)",
      "// Project: #{project.name}",
      ""
    ]
  end

  # ---------------------------------------------------------------------------
  # Variable declarations
  # ---------------------------------------------------------------------------

  defp variable_declaration_lines([]), do: []

  defp variable_declaration_lines(variables) do
    lines =
      Enum.map(variables, fn var ->
        ink_name = Helpers.shortcut_to_identifier(var.full_ref)
        value = Helpers.format_var_declaration_value(var)
        "VAR #{ink_name} = #{value}"
      end)

    ["// === Variables ===" | lines] ++ [""]
  end

  # ---------------------------------------------------------------------------
  # Flow → Knot
  # ---------------------------------------------------------------------------

  defp flow_to_knot(flow, speaker_map, flow_shortcuts_by_id, tunnel_targets) do
    knot_name = Helpers.shortcut_to_identifier(flow.shortcut || flow.name || "flow_#{flow.id}")
    {instructions, hub_sections} = GraphTraversal.linearize_blocks(flow)
    is_tunnel = MapSet.member?(tunnel_targets, flow.shortcut)

    ctx = %{
      speaker_map: speaker_map,
      is_tunnel: is_tunnel,
      flow_shortcuts_by_id: flow_shortcuts_by_id
    }

    body = render_body(instructions, ctx, 0)

    knot_lines =
      [
        "// === Flow: #{flow.name} ===",
        "=== #{knot_name} ===",
        ""
      ] ++ body

    hub_lines =
      Enum.flat_map(hub_sections, fn {label, instrs} ->
        [
          "",
          "= #{label}",
          "" | render_body(instrs, ctx, 0)
        ]
      end)

    knot_lines ++ hub_lines ++ [""]
  end

  # ---------------------------------------------------------------------------
  # Instruction rendering
  # ---------------------------------------------------------------------------

  defp render_instructions(instructions, ctx, depth) do
    render_instruction_stream(instructions, ctx, depth)
  end

  defp render_body(instructions, ctx, depth) do
    lines = render_instructions(instructions, ctx, depth)

    cond do
      lines == [] -> [terminal_line(ctx, depth)]
      instructions_end_flow?(instructions) -> lines
      true -> lines ++ [terminal_line(ctx, depth)]
    end
  end

  defp render_instruction_stream([], _ctx, _depth), do: []

  defp render_instruction_stream([{:choices_start, node} | rest], ctx, depth) do
    {choice_instructions, rest} =
      Enum.split_while(rest, fn
        {:choices_end, _node} -> false
        _instruction -> true
      end)

    rest =
      case rest do
        [{:choices_end, _node} | tail] -> tail
        tail -> tail
      end

    render_choice_instructions(choice_instructions, Map.put(ctx, :choice_owner, node), depth) ++
      render_instruction_stream(rest, ctx, depth)
  end

  defp render_instruction_stream([instruction | rest], ctx, depth) do
    render_instruction(instruction, ctx, depth) ++ render_instruction_stream(rest, ctx, depth)
  end

  defp render_choice_instructions(instructions, ctx, depth) do
    instructions
    |> choice_blocks([])
    |> Enum.map(fn {{:choice, response, index}, body} -> {response, index, body} end)
    |> render_choice_branches(ctx, depth)
  end

  defp render_choice_branches(branches, ctx, depth) do
    Enum.flat_map(branches, fn {response, index, body} ->
      choice_lines = render_instruction({:choice, response, index}, ctx, depth)
      body_lines = render_instructions(body, ctx, depth + 1)
      terminal_lines = if instructions_end_flow?(body), do: [], else: [terminal_line(ctx, depth + 1)]

      choice_lines ++ body_lines ++ terminal_lines
    end)
  end

  defp choice_blocks([], acc), do: Enum.reverse(acc)

  defp choice_blocks([{:choice, _resp, _idx} = choice | rest], acc) do
    {body, rest} =
      Enum.split_while(rest, fn
        {:choice, _resp, _idx} -> false
        _instruction -> true
      end)

    choice_blocks(rest, [{choice, body} | acc])
  end

  defp choice_blocks([_instruction | rest], acc), do: choice_blocks(rest, acc)

  defp instructions_end_flow?(instructions) do
    case List.last(instructions) do
      {:exit, _node} -> true
      {:jump, _node, _target_label} -> true
      {:divert, _target_label} -> true
      _instruction -> false
    end
  end

  defp render_instruction({:dialogue, node}, ctx, depth) do
    data = node.data || %{}
    text = data |> Helpers.dialogue_text() |> escape_ink_text()
    speaker = Helpers.speaker_name(data, ctx.speaker_map)

    shortcut =
      data |> Helpers.speaker_shortcut(ctx.speaker_map) |> Helpers.shortcut_to_identifier()

    line =
      if speaker && shortcut != "" do
        "#{indent(depth)}#{text} #speaker:#{shortcut} #{localization_tag(node, "text")}"
      else
        "#{indent(depth)}#{text} #{localization_tag(node, "text")}"
      end

    stage = data["stage_directions"]

    if stage && stage != "" do
      ["#{indent(depth)}// [Stage: #{Helpers.strip_html(stage)}]", line]
    else
      [line]
    end
  end

  defp render_instruction({:choices_start, _node}, _ctx, _depth), do: []

  defp render_instruction({:choices, node, branches}, ctx, depth) do
    render_choice_branches(branches, Map.put(ctx, :choice_owner, node), depth)
  end

  defp render_instruction({:choice, resp, index}, ctx, depth) do
    text = (resp["text"] || "") |> Helpers.strip_html() |> escape_ink_text()
    condition = build_condition_prefix(resp["condition"])

    choice_line =
      if condition do
        "#{indent(depth)}+ #{condition}[#{text}]"
      else
        "#{indent(depth)}+ [#{text}]"
      end

    choice_line = choice_line <> response_localization_tag(ctx[:choice_owner], resp, index)

    # Response-level instructions
    assign_lines =
      case resp["instruction_assignments"] do
        [_ | _] = assignments ->
          case ExpressionTranspiler.transpile_instruction(assignments, :ink) do
            {:ok, expr, _} when expr != "" ->
              expr |> String.split("\n") |> Enum.map(&"#{indent(depth + 1)}#{&1}")

            _ ->
              []
          end

        _ ->
          []
      end

    [choice_line | assign_lines]
  end

  defp render_instruction({:choices_end, _node}, _ctx, _depth), do: []

  defp render_instruction({:condition, node, branches}, ctx, depth) do
    render_instruction({:condition_start, node}, ctx, depth) ++
      Enum.flat_map(branches, fn {pin, label, index, body} ->
        render_instruction({:condition_branch, pin, label, index}, ctx, depth) ++
          render_instructions(body, ctx, depth)
      end) ++
      render_instruction({:condition_end, node}, ctx, depth)
  end

  defp render_instruction({:condition_start, node}, _ctx, depth) do
    data = node.data || %{}
    condition = Helpers.extract_condition(data["condition"])

    case ExpressionTranspiler.transpile_condition(condition, :ink) do
      {:ok, expr, _} when expr != "" ->
        ["#{indent(depth)}{", "#{indent(depth)}- #{expr}:"]

      _ ->
        ["#{indent(depth)}{", "#{indent(depth)}- true:"]
    end
  end

  # C1 fix: use "- else:" instead of "- Label:" for second branch
  # M3 fix: for 3+ branches, merge into else with comment (Ink only supports if/else)
  defp render_instruction({:condition_branch, _pin, _label, 0}, _ctx, _depth), do: []

  defp render_instruction({:condition_branch, _pin, _label, 1}, _ctx, depth) do
    ["#{indent(depth)}- else:"]
  end

  defp render_instruction({:condition_branch, _pin, label, _idx}, _ctx, depth) do
    ["#{indent(depth)}// (merged branch: #{label})"]
  end

  defp render_instruction({:condition_end, _node}, _ctx, depth) do
    ["#{indent(depth)}}"]
  end

  defp render_instruction({:instruction, node}, _ctx, depth) do
    data = node.data || %{}
    assignments = Helpers.extract_assignments(data)

    case ExpressionTranspiler.transpile_instruction(assignments, :ink) do
      {:ok, expr, _} when expr != "" ->
        expr |> String.split("\n") |> Enum.map(&"#{indent(depth)}#{&1}")

      _ ->
        []
    end
  end

  defp render_instruction({:subflow, node}, ctx, depth) do
    data = node.data || %{}
    target = Helpers.shortcut_to_identifier(resolve_flow_shortcut(data, ctx) || "subflow_#{node.id}")
    ["#{indent(depth)}-> #{target} ->"]
  end

  defp render_instruction({:jump, _node, target_label}, _ctx, depth) do
    ["#{indent(depth)}-> #{target_label}"]
  end

  defp render_instruction({:divert, target_label}, _ctx, depth) do
    ["#{indent(depth)}-> #{target_label}"]
  end

  defp render_instruction({:exit, node}, ctx, depth) do
    data = node.data || %{}

    case data["exit_mode"] do
      "flow_reference" ->
        target = Helpers.shortcut_to_identifier(resolve_flow_shortcut(data, ctx) || "unknown")
        ["#{indent(depth)}-> #{target}"]

      "caller_return" ->
        ["#{indent(depth)}->->"]

      _mode ->
        [terminal_line(ctx, depth)]
    end
  end

  defp render_instruction(_, _ctx, _depth), do: []

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp escape_ink_text(text) do
    text
    |> String.replace("\\", "\\\\")
    |> String.replace("#", "\\#")
    |> String.replace("{", "\\{")
    |> String.replace("}", "\\}")
    |> String.replace("[", "\\[")
    |> String.replace("]", "\\]")
    |> escape_ink_line_starts()
  end

  defp escape_ink_line_starts(text) do
    Regex.replace(~r/(^|\n)(\s*)([-=*+])/, text, "\\1\\2\\\\\\3")
  end

  defp localization_tag(node, source_field) do
    "#storyarn_loc:#{LocalizationCatalog.for_flow_node(node, source_field)}"
  end

  defp response_localization_tag(nil, _response, _index), do: ""

  defp response_localization_tag(node, response, _index) do
    response_id = Map.fetch!(response, "id")
    " #{localization_tag(node, "response.#{response_id}.text")}"
  end

  defp terminal_line(%{is_tunnel: true}, depth), do: "#{indent(depth)}->->"
  defp terminal_line(_ctx, depth), do: "#{indent(depth)}-> END"

  defp flow_shortcuts_by_id(flows) do
    Map.new(flows, fn flow -> {to_string(flow.id), flow.shortcut} end)
  end

  defp collect_tunnel_targets(flows, flow_shortcuts_by_id) do
    flows
    |> Enum.flat_map(fn flow ->
      (flow.nodes || [])
      |> Enum.filter(&(&1.type == "subflow"))
      |> Enum.map(&resolve_flow_shortcut(&1.data || %{}, flow_shortcuts_by_id))
      |> Enum.reject(&blank?/1)
    end)
    |> MapSet.new()
  end

  defp resolve_flow_shortcut(data, %{flow_shortcuts_by_id: flow_shortcuts_by_id}) do
    resolve_flow_shortcut(data, flow_shortcuts_by_id)
  end

  defp resolve_flow_shortcut(data, flow_shortcuts_by_id) do
    data["flow_shortcut"] ||
      data["referenced_flow_shortcut"] ||
      flow_shortcuts_by_id[to_string(data["referenced_flow_id"])]
  end

  defp blank?(nil), do: true
  defp blank?(""), do: true
  defp blank?(_value), do: false

  defp indent(0), do: ""
  defp indent(n), do: String.duplicate("    ", n)

  defp build_condition_prefix(nil), do: nil
  defp build_condition_prefix(""), do: nil

  defp build_condition_prefix(condition) do
    parsed = Helpers.extract_condition(condition)

    case ExpressionTranspiler.transpile_condition(parsed, :ink) do
      {:ok, expr, _} when expr != "" -> "{#{expr}} "
      _ -> nil
    end
  end

  # ---------------------------------------------------------------------------
  # Metadata sidecar
  # ---------------------------------------------------------------------------

  defp build_metadata(project, sheets, variables) do
    characters =
      Map.new(sheets, fn sheet ->
        props =
          sheet.blocks
          |> Enum.filter(&SourceContract.exported_block?/1)
          |> Map.new(fn block ->
            {block.variable_name, Helpers.infer_default_value(block)}
          end)

        {sheet.shortcut, %{"name" => sheet.name, "properties" => props}}
      end)

    variable_mapping =
      Map.new(variables, fn var ->
        {var.full_ref, Helpers.shortcut_to_identifier(var.full_ref)}
      end)

    %{
      "storyarn_ink_metadata" => "1.0.0",
      "project" => project.name,
      "characters" => characters,
      "variable_mapping" => variable_mapping
    }
  end
end
