<script setup lang="ts">
import { CircleHelp } from "@lucide/vue";
import { useI18n } from "vue-i18n";
import { SettingsPage } from "@components/settings";
import { Button } from "@components/ui/button";
import ExportPanel from "@modules/projects/settings/export-import/components/ExportPanel.vue";
import ImportPanel from "@modules/projects/settings/export-import/components/ImportPanel.vue";
import type { ExportConfig, ImportState } from "@modules/projects/settings/export-import/types";
import type { UploadConfig } from "live_vue";

/**
 * Export and Import are two settings pages served by one LiveView; `mode`
 * picks which panel this mount renders.
 */
const {
  mode,
  exportConfig,
  canEdit,
  canImport,
  resumeStorageKey,
  importState,
  uploadConfig = null,
} = defineProps<{
  mode: "export" | "import";
  exportConfig: ExportConfig;
  /** `:edit_content` — export is available to editors. */
  canEdit: boolean;
  /** `:manage_project` — import rewrites project content, so it is owner-only. */
  canImport: boolean;
  /** Opaque browser-storage namespace generated by the server. */
  resumeStorageKey: string;
  importState: ImportState;
  uploadConfig?: UploadConfig | null;
}>();

const { t } = useI18n();

// The onboarding dialog lives in the settings layout, a separate Vue app.
function openTutorial(): void {
  window.dispatchEvent(new CustomEvent("storyarn:open-tutorial"));
}
</script>

<template>
  <SettingsPage
    v-if="mode === 'import'"
    :title="t('project_settings.import.page_title')"
    data-testid="project-settings-import"
  >
    <ImportPanel
      :key="canImport ? 'import-enabled' : 'import-disabled'"
      :can-import="canImport"
      :resume-storage-key="resumeStorageKey"
      :import-state="importState"
      :upload-config="uploadConfig"
    />
  </SettingsPage>

  <SettingsPage
    v-else
    :title="t('project_settings.export.page_title')"
    data-testid="project-settings-export"
  >
    <template #actions>
      <Button
        type="button"
        variant="ghost"
        size="sm"
        data-testid="export-view-tutorial"
        @click="openTutorial"
      >
        <CircleHelp class="size-4" aria-hidden="true" />
        {{ t("onboarding.common.view_tutorial") }}
      </Button>
    </template>

    <ExportPanel
      :can-export="canEdit"
      :format-config="exportConfig.formatConfig"
      :section-config="exportConfig.sectionConfig"
      :options="exportConfig.options"
      :validation="exportConfig.validation"
      :export-download-url="exportConfig.downloadUrl"
    />
  </SettingsPage>
</template>
