<script setup lang="ts">
import ExportPanel from "@modules/projects/settings/export-import/components/ExportPanel.vue";
import ImportPanel from "@modules/projects/settings/export-import/components/ImportPanel.vue";
import type { ExportConfig, ImportState } from "@modules/projects/settings/export-import/types";
import type { UploadConfig } from "live_vue";

const { exportConfig, canEdit, canImport, resumeStorageKey, importState, uploadConfig } =
  defineProps<{
    exportConfig: ExportConfig;
    /** `:edit_content` — export is available to editors. */
    canEdit: boolean;
    /** `:manage_project` — import rewrites project content, so it is owner-only. */
    canImport: boolean;
    /** Opaque browser-storage namespace generated by the server. */
    resumeStorageKey: string;
    importState: ImportState;
    uploadConfig?: UploadConfig | null;
  }>();
</script>

<template>
  <div class="space-y-10">
    <ImportPanel
      :key="canImport ? 'import-enabled' : 'import-disabled'"
      :can-import="canImport"
      :resume-storage-key="resumeStorageKey"
      :import-state="importState"
      :upload-config="uploadConfig"
    />

    <div aria-hidden="true" class="h-px bg-border" />

    <ExportPanel
      :can-export="canEdit"
      :format-config="exportConfig.formatConfig"
      :section-config="exportConfig.sectionConfig"
      :options="exportConfig.options"
      :validation="exportConfig.validation"
      :export-download-url="exportConfig.downloadUrl"
    />
  </div>
</template>
