<script setup lang="ts">
import { computed, type Component } from "vue";
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Bookmark,
  BookmarkPlus,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CloudUpload,
  Columns2,
  Download,
  File,
  Footprints,
  GitBranch,
  GitMerge,
  Image,
  ImagePlus,
  Info,
  Languages,
  Link,
  Loader,
  LoaderCircle,
  Lock,
  Mail,
  Menu,
  MessageCircle,
  Monitor,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  Music,
  Package,
  PanelLeft,
  PanelLeftClose,
  PanelsTopLeft,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  ShieldQuestion,
  Sparkles,
  Star,
  Sun,
  Trash2,
  Upload,
  User,
  Users,
  Variable,
  X,
  XCircle,
} from "lucide-vue-next";

const iconMap: Record<string, Component> = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "bar-chart-3": BarChart3,
  "book-open": BookOpen,
  bookmark: Bookmark,
  "bookmark-plus": BookmarkPlus,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clock: Clock,
  "cloud-upload": CloudUpload,
  "columns-2": Columns2,
  download: Download,
  file: File,
  footprints: Footprints,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  image: Image,
  "image-plus": ImagePlus,
  info: Info,
  languages: Languages,
  link: Link,
  loader: Loader,
  "loader-circle": LoaderCircle,
  lock: Lock,
  mail: Mail,
  menu: Menu,
  "message-circle": MessageCircle,
  monitor: Monitor,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "mouse-pointer-click": MousePointerClick,
  music: Music,
  package: Package,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  "panels-top-left": PanelsTopLeft,
  pencil: Pencil,
  plus: Plus,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  save: Save,
  search: Search,
  settings: Settings,
  "shield-question": ShieldQuestion,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  "trash-2": Trash2,
  upload: Upload,
  user: User,
  users: Users,
  variable: Variable,
  x: X,
  "x-circle": XCircle,
};

const { name, iconClass = "size-4" } = defineProps<{
  name: string;
  iconClass?: string;
}>();

const iconComponent = computed(() => iconMap[name] ?? null);
</script>

<template>
  <component :is="iconComponent" v-if="iconComponent" :class="iconClass" />
</template>
